apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-ledger.fullname" . }}
  labels: {{- include "project-ledger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "project-ledger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "project-ledger.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/api/metrics"
        prometheus.io/port: "3000"
    spec:
      serviceAccountName: {{ include "project-ledger.fullname" . }}
      securityContext: {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: console
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: url
            - name: PL_TRILLIAN_URL
              value: {{ .Values.trillian.url | quote }}
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          livenessProbe:
            httpGet: { path: /api/health, port: http }
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet: { path: /api/ready, port: http }
            periodSeconds: 5
            failureThreshold: 2
          resources: {{- toYaml .Values.resources | nindent 12 }}
