{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "project-ledger.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels: {{- include "project-ledger.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "project-ledger.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /api/metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
